"""add_subscription_type

Revision ID: 4ce72fcb33d4
Revises: b3c4d5e6f7a8
Create Date: 2026-04-24 09:11:53.450689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4ce72fcb33d4'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_reviews_id', table_name='business_reviews')
    op.drop_index('ix_business_reviews_uuid', table_name='business_reviews')
    op.drop_table('business_reviews')
    op.add_column('businesses', sa.Column('upi_id', sa.String(length=100), nullable=True))
    op.add_column('businesses', sa.Column('subscription_type', sa.String(length=10), nullable=True))
    op.drop_index('ix_businesses_uuid_unique', table_name='businesses')
    op.drop_index('ix_businesses_uuid', table_name='businesses')
    op.create_index(op.f('ix_businesses_uuid'), 'businesses', ['uuid'], unique=True)
    op.drop_index('ix_categories_uuid_unique', table_name='categories')
    op.create_unique_constraint(None, 'categories', ['uuid'])
    op.drop_index('ix_customers_uuid_unique', table_name='customers')
    op.create_unique_constraint(None, 'customers', ['uuid'])
    op.alter_column('orders', 'payment_proof_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('ix_orders_uuid_unique', table_name='orders')
    op.drop_index('ix_orders_uuid', table_name='orders')
    op.create_index(op.f('ix_orders_uuid'), 'orders', ['uuid'], unique=True)
    op.drop_constraint('plan_limits_business_id_key', 'plan_limits', type_='unique')
    op.drop_index('ix_plan_limits_business_id', table_name='plan_limits')
    op.create_index(op.f('ix_plan_limits_business_id'), 'plan_limits', ['business_id'], unique=True)
    op.drop_index('ix_products_uuid_unique', table_name='products')
    op.create_unique_constraint(None, 'products', ['uuid'])
    op.drop_index('ix_users_aadhaar_number', table_name='users')
    op.drop_column('users', 'aadhaar_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aadhaar_number', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.create_index('ix_users_aadhaar_number', 'users', ['aadhaar_number'], unique=False)
    op.drop_constraint(None, 'products', type_='unique')
    op.create_index('ix_products_uuid_unique', 'products', ['uuid'], unique=False)
    op.drop_index(op.f('ix_plan_limits_business_id'), table_name='plan_limits')
    op.create_index('ix_plan_limits_business_id', 'plan_limits', ['business_id'], unique=False)
    op.create_unique_constraint('plan_limits_business_id_key', 'plan_limits', ['business_id'])
    op.drop_index(op.f('ix_orders_uuid'), table_name='orders')
    op.create_index('ix_orders_uuid', 'orders', ['uuid'], unique=False)
    op.create_index('ix_orders_uuid_unique', 'orders', ['uuid'], unique=False)
    op.alter_column('orders', 'payment_proof_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'customers', type_='unique')
    op.create_index('ix_customers_uuid_unique', 'customers', ['uuid'], unique=False)
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index('ix_categories_uuid_unique', 'categories', ['uuid'], unique=False)
    op.drop_index(op.f('ix_businesses_uuid'), table_name='businesses')
    op.create_index('ix_businesses_uuid', 'businesses', ['uuid'], unique=False)
    op.create_index('ix_businesses_uuid_unique', 'businesses', ['uuid'], unique=False)
    op.drop_column('businesses', 'subscription_type')
    op.drop_column('businesses', 'upi_id')
    op.create_table('business_reviews',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='business_reviews_business_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='business_reviews_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='business_reviews_pkey')
    )
    op.create_index('ix_business_reviews_uuid', 'business_reviews', ['uuid'], unique=False)
    op.create_index('ix_business_reviews_id', 'business_reviews', ['id'], unique=False)
    # ### end Alembic commands ###
