"""multi_image_support

Revision ID: 8e97915ad4d0
Revises: 69520d0d831c
Create Date: 2026-04-08 15:32:21.553011

"""
from alembic import op
import sqlalchemy as sa

revision = '8e97915ad4d0'
down_revision = '69520d0d831c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('businesses', sa.Column('profile_image_urls', sa.JSON(), nullable=True))
    # op.drop_column('businesses', 'logo_url')
    # op.add_column('plan_limits', sa.Column('max_product_images', sa.Integer(), nullable=True))
    # op.add_column('plan_limits', sa.Column('max_profile_images', sa.Integer(), nullable=True))
    # op.drop_index(op.f('ix_plan_limits_business_id'), table_name='plan_limits')
    # op.create_index(op.f('ix_plan_limits_business_id'), 'plan_limits', ['business_id'], unique=True)
    op.add_column('products', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.drop_column('products', 'image_url')
    op.drop_index(op.f('ix_users_email_unique'), table_name='users')
    op.drop_index(op.f('ix_users_phone_unique'), table_name='users')
    op.drop_index(op.f('ix_users_uuid_unique'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_uuid_unique'), 'users', ['uuid'], unique=True)
    op.create_index(op.f('ix_users_phone_unique'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_email_unique'), 'users', ['email'], unique=True)
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.drop_column('products', 'image_urls')
    op.drop_index(op.f('ix_plan_limits_business_id'), table_name='plan_limits')
    op.create_index(op.f('ix_plan_limits_business_id'), 'plan_limits', ['business_id'], unique=False)
    op.drop_column('plan_limits', 'max_profile_images')
    op.drop_column('plan_limits', 'max_product_images')
    op.add_column('businesses', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.drop_column('businesses', 'profile_image_urls')
    # ### end Alembic commands ###
