class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'English': {
      'dashboard': 'Dashboard',
      'products': 'Products',
      'inventory': 'Inventory',
      'categories': 'Categories',
      'customers': 'Customers',
      'orders': 'Orders',
      'business_profile': 'Business Profile',
      'reports': 'Reports',
      'language': 'Language',
      'logout': 'Logout',
      'recent_orders': 'Recent Orders',
      'revenue': 'Revenue',
      'total_revenue': 'Total Revenue',
      'active_products': 'Active Products',
      'deal_of_the_day': 'Deal of the Day',
      'quick_links': 'Quick Links',
      'contact_info': 'Contact Information',
      'business_details': 'Business Details',
      'location': 'Location',
      'payment_settings': 'Payment Settings',
      'address': 'Address',
      'city': 'City',
      'state': 'State',
      'pincode': 'Pincode',
      'type': 'Type',
      'upi': 'UPI ID',
      'phone': 'Phone',
      'email': 'Email',
      'customer_feedback': 'Customer Feedback',
      // Common Actions
      'edit': 'Edit',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'save': 'Save',
      'add': 'Add',
      'retry': 'Retry',
      'search': 'Search',
      'error': 'Error',
      'success': 'Success',
      'filter': 'Filter',
      'apply_filters': 'Apply Filters',
      // Statuses
      'active': 'Active',
      'inactive': 'Inactive',
      'pending': 'Pending',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      // Product / Inventory
      'product_details': 'Product Details',
      'edit_product': 'Edit Product',
      'add_product': 'Add Product',
      'product_name': 'Product Name',
      'product_name_hint': 'Enter product name',
      'description': 'Description',
      'sku': 'SKU',
      'price': 'Price',
      'cost_price': 'Cost Price',
      'profit_margin': 'Profit Margin',
      'stock_quantity': 'Stock Quantity',
      'unit': 'Unit',
      'out_of_stock': 'Out of Stock',
      'low_stock_alert': 'Low Stock Alert',
      'pricing': 'Pricing',
      'product_info': 'Product Info',
      'created': 'Created',
      'last_updated': 'Last Updated',
      'no_products_found': 'No products found',
      'add_first_product_hint': 'Click the + button to add your first product',
      'search_products': 'Search products...',
      'filter_products': 'Filter Products',
      'all_products': 'All Products',
      'product_status_updated': 'Product status updated',
      'product_deleted_success': 'Product deleted successfully',
      'product_not_found': 'Product not found',
      'field_required': 'This field is required',
      'price_required': 'Price is required',
      'invalid_price': 'Invalid price',
      'stock_required': 'Stock is required',
      'invalid_quantity': 'Invalid quantity',
      'save_product_first': 'Save product first to upload images',
      'upload_new_images': 'Upload New Images',
      // Customer
      'add_customer': 'Add Customer',
      'edit_customer': 'Edit Customer',
      'delete_customer': 'Delete Customer',
      'no_customers_found': 'No customers found',
      'add_first_customer_hint': 'Add your first customer to track their orders',
      'search_customers': 'Search customers...',
      'filter_customers': 'Filter Customers',
      'all_customers': 'All Customers',
      'customer_deleted_success': 'Customer deleted successfully',
      'delete_customer_confirm': 'Are you sure you want to delete this customer?',
      'customer': 'Customer',
      // Order
      'order_details': 'Order Details',
      'no_orders_found': 'No orders found',
      'search_orders': 'Search orders...',
      'filter_orders': 'Filter Orders',
      'walk_in_customer': 'Walk-in Customer',
      'total_amount': 'Total Amount',
      'order_date': 'Order Date',
      // Category
      'add_category': 'Add Category',
      'edit_category': 'Edit Category',
      'delete_category': 'Delete Category',
      'no_categories_found': 'No categories found',
      'search_categories': 'Search categories...',
      'category_name': 'Category Name',
      'category_name_hint': 'Enter category name',
      'category_description_hint': 'Enter category description',
      'category_created_success': 'Category created successfully',
      'category_updated_success': 'Category updated successfully',
      'update_category': 'Update Category',
      'create_category': 'Create Category',
      'no_category': 'No Category',
      'category_active_hint': 'Visible in storefront',
      'category_inactive_hint': 'Hidden from storefront',
    },
    'Tamil': {
      'dashboard': 'முகப்பு',
      'products': 'தயாரிப்புகள்',
      'inventory': 'சரக்கு',
      'categories': 'வகைகள்',
      'customers': 'வாடிக்கையாளர்கள்',
      'orders': 'ஆர்டர்கள்',
      'business_profile': 'வணிக சுயவிவரம்',
      'reports': 'அறிக்கைகள்',
      'language': 'மொழி',
      'logout': 'வெளியேறு',
      'recent_orders': 'சமீபத்திய ஆர்டர்கள்',
      'revenue': 'வருவாய்',
      'total_revenue': 'மொத்த வருவாய்',
      'active_products': 'செயலில் உள்ள தயாரிப்புகள்',
      'deal_of_the_day': 'இன்றைய சலுகை',
      'quick_links': 'விரைவான இணைப்புகள்',
      'contact_info': 'தொடர்பு விவரங்கள்',
      'business_details': 'வணிக விவரங்கள்',
      'location': 'இருப்பிடம்',
      'payment_settings': 'கட்டண அமைப்புகள்',
      'address': 'முகவரி',
      'city': 'நகரம்',
      'state': 'மாநிலம்',
      'pincode': 'அஞ்சல் குறியீடு',
      'type': 'வகை',
      'upi': 'UPI ஐடி',
      'phone': 'தொலைபேசி',
      'email': 'மின்னஞ்சல்',
      'customer_feedback': 'வாடிக்கையாளர் கருத்து',
    },
    'Hindi': {
      'dashboard': 'डैशबोर्ड',
      'products': 'उत्पाद',
      'inventory': 'इन्वेंटरी',
      'categories': 'श्रेणियाँ',
      'customers': 'ग्राहक',
      'orders': 'ऑर्डर',
      'business_profile': 'व्यापार प्रोफ़ाइल',
      'reports': 'रिपोर्ट',
      'language': 'भाषा',
      'logout': 'लॉग आउट',
      'recent_orders': 'हाल के ऑर्डर',
      'revenue': 'राजस्व',
      'total_revenue': 'कुल राजस्व',
      'active_products': 'सक्रिय उत्पाद',
      'deal_of_the_day': 'आज का सौदा',
      'quick_links': 'त्वरित लिंक',
      'contact_info': 'संपर्क जानकारी',
      'business_details': 'व्यापार विवरण',
      'location': 'स्थान',
      'payment_settings': 'भुगतान सेटिंग्स',
      'address': 'पता',
      'city': 'शहर',
      'state': 'राज्य',
      'pincode': 'पिनकोड',
      'type': 'प्रकार',
      'upi': 'UPI आईडी',
      'phone': 'फ़ोन',
      'email': 'ईमेल',
    },
    'Bengali': {
      'dashboard': 'ড্যাশবোর্ড',
      'products': 'পণ্য',
      'inventory': 'মজুত',
      'categories': 'বিভাগ',
      'customers': 'গ্রাহক',
      'orders': 'অর্ডার',
      'business_profile': 'ব্যবসা প্রোফাইল',
      'reports': 'রিপোর্ট',
      'language': 'ভাষা',
      'logout': 'লগআউট',
      'recent_orders': 'সাম্প্রতিক অর্ডার',
      'revenue': 'রাজস্ব',
      'total_revenue': 'মোট রাজস্ব',
      'active_products': 'সক্রিয় পণ্য',
      'deal_of_the_day': 'আজকের সেরা ডিল',
      'quick_links': 'গুরুত্বপূর্ণ লিংক',
      'contact_info': 'যোগাযোগের তথ্য',
      'business_details': 'ব্যবসার বিবরণ',
      'location': 'অবস্থান',
      'payment_settings': 'পেমেন্ট সেটিং',
      'address': 'ঠিকানা',
      'city': 'শহর',
      'state': 'রাজ্য',
      'pincode': 'পিনকোড',
      'type': 'ধরণ',
      'upi': 'UPI আইডি',
      'phone': 'ফোন',
      'email': 'ইমেইল',
      'customer_feedback': 'গ্রাহক প্রতিক্রিয়া',
    },
    'Marathi': {
      'dashboard': 'डॅशबोर्ड',
      'products': 'उत्पादने',
      'inventory': 'इन्व्हेन्टरी',
      'categories': 'श्रेणी',
      'customers': 'ग्राहक',
      'orders': 'ऑर्डर्स',
      'business_profile': 'व्यवसाय प्रोफाइल',
      'reports': 'अहवाल',
      'language': 'भाषा',
      'logout': 'बाहेर पडा',
      'recent_orders': 'अलीकडील ऑर्डर्स',
      'revenue': 'महसूल',
      'total_revenue': 'एकूण महसूल',
      'active_products': 'सक्रिय उत्पादने',
      'deal_of_the_day': 'आजचा उत्तम करार',
      'quick_links': 'त्वरित दुवे',
      'contact_info': 'संपर्क माहिती',
      'business_details': 'व्यवसाय तपशील',
      'location': 'स्थान',
      'payment_settings': 'पेमेंट सेटिंग्ज',
      'address': 'पत्ता',
      'city': 'शहर',
      'state': 'राज्य',
      'pincode': 'पिनकोड',
      'type': 'प्रकार',
      'upi': 'UPI आयडी',
      'phone': 'फोन',
      'email': 'ईमेल',
    },
    'Telugu': {
      'dashboard': 'డాష్బోర్డ్',
      'products': 'ఉత్పత్తులు',
      'inventory': 'జాబితా',
      'categories': 'వర్గాలు',
      'customers': 'ఖాతాదారులు',
      'orders': 'ఆర్డర్లు',
      'business_profile': 'వ్యాపార ప్రొఫైల్',
      'reports': 'నివేదికలు',
      'language': 'భాష',
      'logout': 'లాగ్ అవుట్',
      'recent_orders': 'ఇటీవలి ఆర్డర్లు',
      'revenue': 'రాబడి',
      'total_revenue': 'మొత్తం రాబడి',
      'active_products': 'క్రియాశీల ఉత్పత్తులు',
      'deal_of_the_day': 'నేటి ఉత్తమ డీల్',
      'quick_links': 'శీఘ్ర లింక్‌లు',
      'contact_info': 'సంప్రదింపు సమాచారం',
      'business_details': 'వ్యాపార వివరాలు',
      'location': 'స్థానం',
      'payment_settings': 'చెల్లింపు సెట్టింగ్‌లు',
      'address': 'చిరునామా',
      'city': 'నగరం',
      'state': 'రాష్ట్రం',
      'pincode': 'పిన్ కోడ్',
      'type': 'రకం',
      'upi': 'UPI ఐడి',
      'phone': 'ఫోన్',
      'email': 'ఈమెయిల్',
      'customer_feedback': 'ఖాతాదారుల అభిప్రాయం',
    },
    'Kannada': {
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'products': 'ಉತ್ಪನ್ನಗಳು',
      'inventory': 'ದಾಸ್ತಾನು',
      'categories': 'ವರ್ಗಗಳು',
      'customers': 'ಗ್ರಾಹಕರು',
      'orders': 'ಆದೇಶಗಳು',
      'business_profile': 'ವ್ಯಾಪಾರ ಪ್ರೊಫೈಲ್',
      'reports': 'ವರದಿಗಳು',
      'language': 'ಭಾಷೆ',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'recent_orders': 'ಇತ್ತೀಚಿನ ಆದೇಶಗಳು',
      'revenue': 'ಆದಾಯ',
      'total_revenue': 'ಒಟ್ಟು ಆದಾಯ',
      'active_products': 'ಸಕ್ರಿಯ ಉತ್ಪನ್ನಗಳು',
      'deal_of_the_day': 'ಇಂದಿನ ಅತ್ಯುತ್ತಮ ಡೀಲ್',
      'quick_links': 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
      'contact_info': 'ಸಂಪರ್ಕ ಮಾಹಿತಿ',
      'business_details': 'ವ್ಯವಹಾರದ ವಿವರಗಳು',
      'location': 'ಸ್ಥಳ',
      'payment_settings': 'ಪಾವತಿ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'address': 'ವಿಳಾಸ',
      'city': 'ನಗರ',
      'state': 'ರಾಜ್ಯ',
      'pincode': 'ಪಿನ್‌ಕೋಡ್',
      'type': 'ವಿಧ',
      'upi': 'UPI ಐಡಿ',
      'phone': 'ದೂರವಾಣಿ',
      'email': 'ಇಮೇಲ್',
      'customer_feedback': 'ಗ್ರಾಹಕರ ಪ್ರತಿಕ್ರಿಯೆ',
    },
    'Malayalam': {
      'dashboard': 'ഡാഷ്‌ബോർഡ്',
      'products': 'ഉൽപ്പന്നങ്ങൾ',
      'inventory': 'ചരക്ക്',
      'categories': 'വിഭാഗങ്ങൾ',
      'customers': 'ഉപഭോക്താക്കൾ',
      'orders': 'ഓർഡറുകൾ',
      'business_profile': 'ബിസിനസ്സ് പ്രൊഫൈൽ',
      'reports': 'റിപ്പോർട്ടുകൾ',
      'language': 'ഭാഷ',
      'logout': 'ലോഗൗട്ട് ചെയ്യുക',
      'recent_orders': 'അടുത്ത കാലത്തായുള്ള ഓർഡറുകൾ',
      'revenue': 'വരുമാനം',
      'total_revenue': 'മൊത്തം വരുമാനം',
      'active_products': 'സജീവ ഉൽപ്പന്നങ്ങൾ',
      'deal_of_the_day': 'ഇന്നത്തെ മികച്ച ഓഫർ',
      'quick_links': 'ദ്രുത ലിങ്കുകൾ',
      'contact_info': 'ബന്ധപ്പെടാനുള്ള വിവരം',
      'business_details': 'ബിസിനസ്സ് വിശദാംശങ്ങൾ',
      'location': 'സ്ഥലം',
      'payment_settings': 'പേയ്‌മെന്റ് ക്രമീകരണങ്ങൾ',
      'address': 'മേൽവിലാസം',
      'city': 'നഗരം',
      'state': 'സംസ്ഥാനം',
      'pincode': 'പിൻകോഡ്',
      'type': 'തരം',
      'upi': 'UPI ഐഡി',
      'phone': 'ഫോൺ',
      'email': 'ഇമെയിൽ',
      'customer_feedback': 'ഉപഭോക്തൃ പ്രതികരണം',
    },
  };

  static String translate(String languageCode, String key) {
    if (_localizedValues.containsKey(languageCode)) {
      if (_localizedValues[languageCode]!.containsKey(key)) {
        return _localizedValues[languageCode]![key]!;
      }
    }
    // Fallback to English
    return _localizedValues['English']?[key] ?? key;
  }
}
